name: 'build-test'
on:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build

  test:
    needs: [build]
    strategy:
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "macos-latest", "windows-latest"]') }}
        version: ["", 1295939, 120, dev, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: ${{ matrix.version }}
          install-chromedriver: true
        id: setup-chrome
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version
      - if: runner.os == 'Windows'
        run: |
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chrome-path }}").Source).VersionInfo.ProductVersion
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chromedriver-path }}").Source).VersionInfo.ProductVersion

  test-windows-arm:
    needs: [build]
    if: github.actor != 'dependabot[bot]'
    runs-on: windows-11-arm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: 1485971
          install-chromedriver: true
        id: setup-chrome
      - run: |
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chrome-path }}").Source).VersionInfo.ProductVersion
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chromedriver-path }}").Source).VersionInfo.ProductVersion

  test-linux-arm:
    needs: [build]
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: canary
          install-chromedriver: true
        id: setup-chrome
      - run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version

  test-install-dependencies:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        container:
          - ""
          - fedora
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Install tar and git (opensuse/leap)
        run: zypper install --no-confirm tar git
        if: ${{ matrix.container == 'opensuse/leap' }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install action dependencies
        run: apt-get update && apt-get install -y unzip
        if: ${{ matrix.container == 'debian' || matrix.container == 'ubuntu' || matrix.container == 'linuxmintd/mint21-amd64' }}
      - name: Install action dependencies
        run: yum install --assumeyes unzip
        if: ${{ matrix.container == 'redhat/ubi9' || matrix.container == 'oraclelinux:9' || matrix.container == 'fedora' }}
      - name: Install action dependencies
        run: zypper install --no-confirm unzip
        if: ${{ matrix.container == 'opensuse/leap' || matrix.container == 'registry.suse.com/bci/bci-base:15.5' }}

      # Override GITHUB_PATH by the current PATH to prevent the issue discussed in https://github.com/actions/runner/issues/3210
      - run: echo "$PATH" >>"$GITHUB_PATH"
        if: ${{ matrix.container == 'opensuse/leap' || matrix.container == 'registry.suse.com/bci/bci-base:15.5' }}

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: 120
          install-chromedriver: true
          install-dependencies: true
        id: setup-chrome
      - run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version
